In [41]:
pip install nltk

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 4.1 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 289.0/289.0 kB 4.0 MB/s eta 0:00:00a 0:00:01

[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
products = pd.read_csv('products.csv')
products.head()

uniq_id            crawl_timestamp  \
0  c2d766ca982eca8304150849735ffef9  2016-03-25 22:59:23 +0000   
1  7f7036a6d550aaa89d34c77bd39a5e48  2016-03-25 22:59:23 +0000   
2  f449ec65dcbc041b6ae5e6a32717d01b  2016-03-25 22:59:23 +0000   
3  0973b37acd0c664e3de26e97e5571454  2016-03-25 22:59:23 +0000   
4  bc940ea42ee6bef5ac7cea3fb5cfbee7  2016-03-25 22:59:23 +0000   

                                         product_url  \
0  http://www.flipkart.com/alisha-solid-women-s-c...   
1  http://www.flipkart.com/fabhomedecor-fabric-do...   
2  http://www.flipkart.com/aw-bellies/p/itmeh4grg...   
3  http://www.flipkart.com/alisha-solid-women-s-c...   
4  http://www.flipkart.com/sicons-all-purpose-arn...   

                            product_name  \
0    Alisha Solid Women's Cycling Shorts   
1    FabHomeDecor Fabric Double Sofa Bed   
2                             AW Bellies   
3    Alisha Solid Women's Cycling Shorts   
4  Sicons All Purpose Arnica Dog Shampoo   

                               product_category_tree               pid  \
0  ["Clothing >> Women's Clothing >> Lingerie, Sl...  SRTEH2FF9KEDEFGF   
1  ["Furniture >> Living Room Furniture >> Sofa B...  SBEEH3QGU7MFYJFY   
2  ["Footwear >> Women's Footwear >> Ballerinas >...  SHOEH4GRSUBJGZXE   
3  ["Clothing >> Women's Clothing >> Lingerie, Sl...  SRTEH2F6HUZMQ6SJ   
4  ["Pet Supplies >> Grooming >> Skin & Coat Care...  PSOEH3ZYDMSYARJ5   

   retail_price  discounted_price  \
0         999.0             379.0   
1       32157.0           22646.0   
2         999.0             499.0   
3         699.0             267.0   
4         220.0             210.0   

                                               image  is_FK_Advantage_product  \
0  ["http://img5a.flixcart.com/image/short/u/4/a/...                    False   
1  ["http://img6a.flixcart.com/image/sofa-bed/j/f...                    False   
2  ["http://img5a.flixcart.com/image/shoe/7/z/z/r...                    False   
3  ["http://img5a.flixcart.com/image/short/6/2/h/...                    False   
4  ["http://img5a.flixcart.com/image/pet-shampoo/...                    False   

                                         description       product_rating  \
0  Key Features of Alisha Solid Women's Cycling S...  No rating available   
1  FabHomeDecor Fabric Double Sofa Bed (Finish Co...  No rating available   
2  Key Features of AW Bellies Sandals Wedges Heel...  No rating available   
3  Key Features of Alisha Solid Women's Cycling S...  No rating available   
4  Specifications of Sicons All Purpose Arnica Do...  No rating available   

        overall_rating         brand  \
0  No rating available        Alisha   
1  No rating available  FabHomeDecor   
2  No rating available            AW   
3  No rating available        Alisha   
4  No rating available        Sicons   

                              product_specifications  
0  {"product_specification"=>[{"key"=>"Number of ...  
1  {"product_specification"=>[{"key"=>"Installati...  
2  {"product_specification"=>[{"key"=>"Ideal For"...  
3  {"product_specification"=>[{"key"=>"Number of ...  
4  {"product_specification"=>[{"key"=>"Pet Type",...

In [3]:
len(products['product_name'].unique()), len(products['uniq_id'].unique())

(12676, 20000)

In [4]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   uniq_id                  20000 non-null  object 
 1   crawl_timestamp          20000 non-null  object 
 2   product_url              20000 non-null  object 
 3   product_name             20000 non-null  object 
 4   product_category_tree    20000 non-null  object 
 5   pid                      20000 non-null  object 
 6   retail_price             19922 non-null  float64
 7   discounted_price         19922 non-null  float64
 8   image                    19997 non-null  object 
 9   is_FK_Advantage_product  20000 non-null  bool   
 10  description              19998 non-null  object 
 11  product_rating           20000 non-null  object 
 12  overall_rating           20000 non-null  object 
 13  brand                    14136 non-null  object 
 14  product_specifications

In [35]:
products['product_category_tree']=products['product_category_tree'].map(lambda x:x.strip('[]'))
products['product_category_tree']=products['product_category_tree'].map(lambda x:x.strip('"'))
products['product_category_tree']=products['product_category_tree'].map(lambda x:x.split('>>'))

In [36]:
products = products.drop(['crawl_timestamp','product_url','image',"retail_price","discounted_price","is_FK_Advantage_product","product_rating","overall_rating","product_specifications"], axis=1)

In [37]:
products.head()

uniq_id                           product_name  \
0  c2d766ca982eca8304150849735ffef9    Alisha Solid Women's Cycling Shorts   
1  7f7036a6d550aaa89d34c77bd39a5e48    FabHomeDecor Fabric Double Sofa Bed   
2  f449ec65dcbc041b6ae5e6a32717d01b                             AW Bellies   
3  0973b37acd0c664e3de26e97e5571454    Alisha Solid Women's Cycling Shorts   
4  bc940ea42ee6bef5ac7cea3fb5cfbee7  Sicons All Purpose Arnica Dog Shampoo   

                               product_category_tree               pid  \
0  [Clothing ,  Women's Clothing ,  Lingerie, Sle...  SRTEH2FF9KEDEFGF   
1  [Furniture ,  Living Room Furniture ,  Sofa Be...  SBEEH3QGU7MFYJFY   
2  [Footwear ,  Women's Footwear ,  Ballerinas , ...  SHOEH4GRSUBJGZXE   
3  [Clothing ,  Women's Clothing ,  Lingerie, Sle...  SRTEH2F6HUZMQ6SJ   
4  [Pet Supplies ,  Grooming ,  Skin & Coat Care ...  PSOEH3ZYDMSYARJ5   

                                         description         brand  
0  Key Features of Alisha Solid Women's Cycling S...        Alisha  
1  FabHomeDecor Fabric Double Sofa Bed (Finish Co...  FabHomeDecor  
2  Key Features of AW Bellies Sandals Wedges Heel...            AW  
3  Key Features of Alisha Solid Women's Cycling S...        Alisha  
4  Specifications of Sicons All Purpose Arnica Do...        Sicons

In [38]:
smd=products.copy()
# drop duplicate produts
smd.drop_duplicates(subset ="product_name", 
                     keep = "first", inplace = True)
smd.shape

(12676, 6)

In [62]:
products['product_category_tree'] = products['product_category_tree'].apply(lambda x: ''.join(x))

In [63]:
products['product_category_tree']

0        Clothing   Women's Clothing   Lingerie, Sleep ...
1        Furniture   Living Room Furniture   Sofa Beds ...
2        Footwear   Women's Footwear   Ballerinas   AW ...
3        Clothing   Women's Clothing   Lingerie, Sleep ...
4        Pet Supplies   Grooming   Skin & Coat Care   S...
                               ...                        
19995    Baby Care   Baby & Kids Gifts   Stickers   Wal...
19996    Baby Care   Baby & Kids Gifts   Stickers   Wal...
19997    Baby Care   Baby & Kids Gifts   Stickers   Eli...
19998    Baby Care   Baby & Kids Gifts   Stickers   Eli...
19999    Baby Care   Baby & Kids Gifts   Stickers   Eli...
Name: product_category_tree, Length: 20000, dtype: object

In [73]:
smd["all_meta"]=smd['product_name']+' '+ smd['brand']+ ' '+ products['product_category_tree']+smd['description']
smd["all_meta"] = smd["all_meta"].fillna('')
smd["all_meta"] = smd["all_meta"].apply(lambda x: x.lower())

In [74]:
smd["all_meta"].head()

0    alisha solid women's cycling shorts alisha clo...
1    fabhomedecor fabric double sofa bed fabhomedec...
2    aw bellies aw footwear   women's footwear   ba...
4    sicons all purpose arnica dog shampoo sicons p...
5    eternal gandhi super series crystal paper weig...
Name: all_meta, dtype: object

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
tfv = TfidfVectorizer(max_features=None,
                     strip_accents='unicode',
                     analyzer='word',
                     min_df=10,
                     token_pattern=r'\w{1,}',
                     ngram_range=(1,3),#take the combination of 1-3 different kind of words
                     stop_words='english')#removes all the unnecessary characters like the,in etc.
products['description'] = products['description'].fillna('')

In [75]:
tfv_matrix = tfv.fit_transform(products['description'])
tfidf_matrix = tfv.fit_transform(smd['all_meta'])

In [12]:
tfv_matrix

<20000x23315 sparse matrix of type '<class 'numpy.float64'>'
	with 1510389 stored elements in Compressed Sparse Row format>

In [13]:
tfv_matrix.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [14]:
tfv_matrix.shape

(20000, 23315)

In [76]:
from sklearn.metrics.pairwise import cosine_similarity
sig = cosine_similarity(tfv_matrix, tfv_matrix)
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

In [17]:
enumerate(sig[1])

In [29]:
indices = pd.Series(products.index,index=products['product_name']).drop_duplicates()

In [30]:
indices

product_name
Alisha Solid Women's Cycling Shorts            0
FabHomeDecor Fabric Double Sofa Bed            1
AW Bellies                                     2
Alisha Solid Women's Cycling Shorts            3
Sicons All Purpose Arnica Dog Shampoo          4
                                           ...  
WallDesign Small Vinyl Sticker             19995
Wallmantra Large Vinyl Stickers Sticker    19996
Elite Collection Medium Acrylic Sticker    19997
Elite Collection Medium Acrylic Sticker    19998
Elite Collection Medium Acrylic Sticker    19999
Length: 20000, dtype: int64

In [17]:
from sklearn.metrics import pairwise_distances
from sklearn.preprocessing import MultiLabelBinarizer

In [18]:
mlb = MultiLabelBinarizer()
product_category_tree = products['product_category_tree'].apply(eval)
category_matrix = mlb.fit_transform(product_category_tree)

In [19]:
category_matrix

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [20]:
jaccard_sim_matrix = 1 - pairwise_distances(category_matrix, metric='jaccard')

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/metrics/pairwise.py:2181: DataConversionWarning: Data was converted to boolean for metric jaccard
  warnings.warn(msg, DataConversionWarning)


In [31]:
jaccard_sim_matrix

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 1., 1.],
       [0., 0., 0., ..., 1., 1., 1.],
       [0., 0., 0., ..., 1., 1., 1.]])

In [33]:
def product_recommendation(title, sig=sig):
    idx = indices[title]
    sig_scores = list(enumerate(sig[idx]))
    sig_scores = sorted(sig_scores, key = lambda x: x[1], reverse=True )
    sig_scores = sig_scores[1:11]
    product_indices = [i[0] for i in sig_scores]
    return products['product_name'].iloc[product_indices]

In [77]:
def get_recommendations(title):
    idx = indices[title]
    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:31]
    product_indices = [i[0] for i in sim_scores]
    return titles.iloc[product_indices]

In [22]:
def jaccard_recommendation(title, jaccard_sim_matrix=jaccard_sim_matrix, indices=indices):
    print(indices[title])
    

    idx = indices[title]
    if idx >= jaccard_sim_matrix.shape[0]:
        print(f"Error: Index '{idx}' is out of range for the jaccard_sim_matrix.")
        return None

    sig_scores = list(enumerate(jaccard_sim_matrix[idx]))
    sig_scores = sorted(sig_scores, key=lambda x: x[1], reverse=True)
    sig_scores = sig_scores[1:11]
    product_indices = [i[0] for i in sig_scores]
    return products['product_name'].iloc[product_indices]

In [25]:
jaccard_recommendation(20)

20


0                  Alisha Solid Women's Cycling Shorts
1                  FabHomeDecor Fabric Double Sofa Bed
2                                           AW Bellies
3                  Alisha Solid Women's Cycling Shorts
4                Sicons All Purpose Arnica Dog Shampoo
5    Eternal Gandhi Super Series Crystal Paper Weig...
6                  Alisha Solid Women's Cycling Shorts
7                  FabHomeDecor Fabric Double Sofa Bed
8    dilli bazaaar Bellies, Corporate Casuals, Casuals
9                  Alisha Solid Women's Cycling Shorts
Name: product_name, dtype: object

In [34]:
product_recommendation(20).unique()

array(['Sicons All Purpose Arnica Dog Shampoo',
       'Sicons All Purpose Tea Tree Dog Shampoo',
       'Magideal Raincoat for Dog',
       'Royal Canin Maxi Starter 1kg Vegetable Dog Food',
       'Four Paws Sweats for Cat, Dog', 'Babyoye Premium Dog Face Bib',
       'Petto Raincoat for Dog, Cat',
       'Wella Elements Leight Weight Renewing Conditioner',
       'L Oreal Eversleek Sulfate - Free Smoothing System Intense Smoothing Shampoo',
       'Four Paws Round Plastic Pet Bottle'], dtype=object)